name: CI 

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm i --save node-pre-gyp    
      - run: npm ci 
      - run: npm install
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
   