name: CI 

on: push
jobs:
  checks:
    name: Test Cache behavior
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v1
      - run: npm install node-pre-gyp
      - run: npm ci
      - run: npm run prettier:check


