# name: Deploy Prod Apps

# on:
#   push:
#     branches:
#       - master

# jobs:
#   InstallDependencies:
#     name: Install Dependencies
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
 

#       - name: Install Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: '14.x'

#       - name: Install libnotify
#         run: sudo apt-get install libnotify-bin

#       - name: Install npm dependencies
#         run: npm install
      
   
#   Build:    
#     name: Build the App
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
 

#       - name: build the project 
#         run:  npm run build

    
name: Build and deploy
on: push


jobs:
  build:
    name: Build ⛏
    runs-on: ubuntu-latest
    steps:


      - name: Checkout repository
        uses: actions/checkout@main


      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
            # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build dependencies
        run: npm run build


      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: dist    
          path: dist





  deploy-via-sftp:
    name: Deploy 🚀
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with: 
          name: dist
          path: dist
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: ${{ secrets.SERVER_USER }}
          server: ${{ secrets.SERVER_HOST }}
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
 

          # will put all file under this path
          local_path: ./dist  # default is ./*
          # files will copy to under remote_path
          remote_path: /home/testDeployment
          # sftp args
          script: systemctl status nginx
          args: '-o ConnectTimeout=5'





  slack-notification:
    name: send slack notification ✉️ 
    needs: deploy-via-sftp
    runs-on: ubuntu-latest
    steps: 
    
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel:  ${{ secrets.Slack_Channel }}
          slack-text: GitHub Action build result "${{ job.status }}" \n 
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
