# name: Deploy app
# on: push
# jobs:
#   build:
#     name: Build App
#     runs-on:  ubuntu-latest
#     steps: 
#     - name: Post to a Slack channel
#       id: slack
#       uses: slackapi/slack-github-action@v1.21.0
#       with:
#         # Slack channel id, channel name, or user id to post message.
#         # See also: https://api.slack.com/methods/chat.postMessage#channels
#         channel-id: 'C0407413RQ8'
#         # For posting a rich message using Block Kit
#         payload: |
#           {
#             "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
#             "blocks": [
#               {
#                 "type": "section",
#                 "text": {
#                   "type": "mrkdwn",
#                   "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
#                 }
#               }
#             ]
#           }
#       env:
#         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}


name: slack-notification

on: [push]

jobs:
  slack-notifications:
    runs-on: ubuntu-20.04
    name: Sends a message to Slack when a push, a pull request or an issue is made
    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel:  ${{ secrets.Slack_Channel }}
          slack-text: Hello georges! Event "${{ github.event_name }}" in "${{ github.repository }}" and commit is "${{ github.event.head_commit.message }}" 
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"