name: ssh command
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ssh pipelines
        uses: appleboy/ssh-action@master
        with:
          host: li2151-203.members.linode.com
          user: root
          key: ${{ secrets.SSH_SECRET }}
          port: 22
          connect_timeout: 10s
          script: |
            ls -la  
            pwd
          