name: ssh command
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.HOST }}
          SSH_PORT: ${{ secrets.PORT }}
          SSH_USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.KEY }}
      - run: pwd