name: ssh command
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        env:
          WELCOME: "ssh pipeline"
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          connect_timeout: 10s
          script: |
            ls -la  
            echo $WELCOME 
            mkdir -p /home/github/test/test1 && 
            mkdir -p /home/github/test/test2 &&