name: Connect through SSH

on: push

jobs:
  pinger_job:
    name: A job to ping
    runs-on: ubuntu-latest
    env:
      URL: ${{ secrets.HOST }}
      METHOD: GET  # the method used to make the request. It is GET by default
    steps:
      - id: ping
        uses: sisodiya2421/pinger@master